title: Neural Navigator Lab

author: Satya Pati

description: >
  Research notes, engineering insights, and experiments in Artificial Intelligence.

email: iamsatyapati@gmail.com

github_username: Neural-Navigator

linkedin_username: iamsatyapati

twitter_username: i_satyapati

plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown

highlighter: rouge

permalink: /:categories/:title/

collections:
  research:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post